spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/caxiasdestiny
    username: caxiasdb
    password: caxiasma99
  jpa:
    database: POSTGRESQL
    hibernate:
      ddl-auto: update
    show-sql: true
